# Imports Verilog, DEF and LEF files from ISPD2015 contest.
# Saves the resulting design in Encounter (.enc) layout
# Execute from folder of each benchmark, e.g.:
#  'ispd_2015_contest_benchmark/mgc_fft_1'
# The placement information generated by EhPlacer is also imported.

# ******************************* Import ***************************************
# Set global variables for init_design command
set init_verilog ./design.v
# Detect top cell automatically
set init_design_top 0
# If automatic detection fails:
# set init_top_cell fft
set init_gnd_net {vss}
# CHECK if direct import of {tech.lef cells.lef} works better
set init_lef_file {./tech.lef ./cells.lef}
init_design
defIn ./floorplan.def
defIn ./EhPlacerOutput.def

# **************** Save full Design in Encounter format ************************
saveDesign ./design_placed.enc
# Save placed layout as OASIS file
setOasisOutMode -cblockCompression true -textSize 1
# TODO Create map file (specific to each layouts layers)
oasisOut design_placed.oas -mapFile ./oasisOut_mgc_fft_1.map  \
    -dieAreaAsBoundary -outputMacros -mode ALL

# Load data from encounter cmd like this
# source design_placed.enc
# And from UNIX command line with
# encounter -init design_placed.enc -no_gui